### ISSUE TITLE
Exception when calling Rrdb.close() under Java 9

### ISSUE THREAD

**Issue by tonyabbott** [rrd4j/rrd4j#107]
Running under Java 9, you get the following exception when calling Rrdb.close() :

Exception in thread "main" java.lang.NoSuchMethodError: sun.nio.ch.DirectBuffer.cleaner()Lsun/misc/Cleaner;
	at org.rrd4j.core.RrdNioBackend.unmapFile(RrdNioBackend.java:72)
	at org.rrd4j.core.RrdNioBackend.close(RrdNioBackend.java:136)
	at org.rrd4j.core.RrdDb.close(RrdDb.java:385)

**Comment by fbacchella** [comment]
Duplicate of #72
