### ISSUE TITLE
Issue in reading rrd file, created by other than rrd4j tool

### ISSUE THREAD

**Issue by cprakash123** [rrd4j/rrd4j#111]
Hi Team,
I have issue for reading rrd file . my rrd file is older and its created by other than rrd4j tool. when ever i trying to read then its throw below exception.

[‎11/‎22/‎2017 6:18 PM] 
Exception in thread "main" java.io.IOException: Invalid file header. File [C:\Users\cp\rrd4j-demo\power.rrd] is not a RRD4J RRD file
	at org.rrd4j.core.Header.validateHeader(Header.java:222)
	at org.rrd4j.core.RrdDb.<init>(RrdDb.java:278)
	at org.rrd4j.core.RrdDb.<init>(RrdDb.java:205)
	at org.rrd4j.core.RrdDb.<init>(RrdDb.java:185)
	at org.rrd4j.demo.Demo1.main(Demo1.java:57) \
Thanks 
Chandra Prakash

**Comment by fbacchella** [comment]
rrd4j is not compatible with rrdtool. But you can have a look to http://rrd4j.org/site/apidocs/index.html.
