### ISSUE TITLE
Exception in thread "main" org.eclipse.rdf4j.rio.RDFParseException: JAXP00010001 

### ISSUE THREAD

**Issue by TamouzeAssi** [rrd4j/rrd4j#122]
I want to read a RDF file A and convert it to another new  RDF File by eliminating some triple from A.

My code is:

```
public class ConvertOntology {

	public static void main(String[] args) throws RDFParseException, RDFHandlerException, IOException {
		// TODO Auto-generated method stub

		String file = "C:\\Users\\user\\Desktop\\eprints-rexa\\fileA.rdf";
		File initialFile = new File(file);
		InputStream input = new FileInputStream(initialFile);


		RDFParser parser = Rio.createParser(RDFFormat.RDFXML);
		parser.setPreserveBNodeIDs(true); 

		Model model = new LinkedHashModel();
		parser.setRDFHandler(new StatementCollector(model));
		parser.parse(input, initialFile.getAbsolutePath());
		
		FileOutputStream out = new FileOutputStream("C:\\Users\\user\\Desktop\\eprints-rexa\\fileB.rdf");
		RDFWriter writer = Rio.createWriter(RDFFormat.RDFXML, out);
		try {
		  writer.startRDF();
		  for (Statement st: model) {
			  if (!st.getPredicate().getLocalName().equals("propertyA") )
				  	writer.handleStatement(st);
		  }
		  writer.endRDF();
		}
		catch (RDFHandlerException e) {
		 // oh no, do something!
		}
		finally {
		  out.close();
		}
	}

}
```

I get the following exception:
```
Exception in thread "main" org.eclipse.rdf4j.rio.RDFParseException: JAXP00010001 : L'analyseur a rencontré plus de "64000" développements d'entité dans ce document. Il s'agit de la limite imposée par le JDK. [line 1, column 1]
	at org.eclipse.rdf4j.rio.helpers.RDFParserHelper.reportFatalError(RDFParserHelper.java:403)
	at org.eclipse.rdf4j.rio.helpers.AbstractRDFParser.reportFatalError(AbstractRDFParser.java:657)
	at org.eclipse.rdf4j.rio.rdfxml.RDFXMLParser.reportFatalError(RDFXMLParser.java:1250)
	at org.eclipse.rdf4j.rio.rdfxml.RDFXMLParser.fatalError(RDFXMLParser.java:1406)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:180)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:284)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.startEntity(XMLEntityManager.java:1317)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.startEntity(XMLEntityManager.java:1241)
	at com.sun.org.apache.xerces.internal.impl.XMLScanner.scanAttributeValue(XMLScanner.java:950)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanAttribute(XMLNSDocumentScannerImpl.java:440)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:256)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2787)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:118)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
	at org.eclipse.rdf4j.rio.rdfxml.RDFXMLParser.parse(RDFXMLParser.java:330)
	at org.eclipse.rdf4j.rio.rdfxml.RDFXMLParser.parse(RDFXMLParser.java:209)
	at ConvertOntology.main(ConvertOntology.java:37)

```

Can please help me and diagnostic where is my error? noting that on small file the code work well.

**Comment by fbacchella** [comment]
Wrong project.
