### ISSUE TITLE
Synchronizations issues on RrdDbPool

### ISSUE THREAD

**Issue by j3rem1e** [rrd4j/rrd4j#125]
RrdDbPool doesn't seem to be really threadsafe :

RrdEntry.count is an integer which is read or written without synchronization, and decisions are taken with the value of this integer. Calling requestRrdDb and release RrdDb could result in unexpected result. Operations on requestRrdDb and releaseRrdDb should probably be synchronized on the RrdEntry

Moreover, the method RrdDbPool.getOpenFiles() could fail with an NPE : it's possible to have on the pool an RrdEntry with a null rrdDb (because it's initializing in another thread by example)

**Comment by fbacchella** [comment]
Did you have any problem with it, any bug ? An active RrdEntry (one with a RrdDb and placeholder set to false) should be used by only one thread for any given time. It uses the kind of swap property of ConcurrentMap.putIfAbsent.

**Comment by j3rem1e** [comment]
You're right, I have misunderstood the "placeholder" concept used in the RrdDbPool, my bad.

After upgrading to rrd4j 3.4, my test suits has a lot of failing tests. However, the issue I have encountered was related to #124 

The code requested an rrddb for a file which was already opened : the request failed but the exception corrupted the pool. for exemple, exceptions thrown here [1] will keep a rrdentry with a null rrddb.

Moreover, I monitor the pool by calling periodically RrdDbPool.getOpenFiles() : this method fails with an NPE because it can see placeholders with a null rrddb reference.

[1] https://github.com/rrd4j/rrd4j/blob/master/src/main/java/org/rrd4j/core/RrdDbPool.java#L354

**Comment by fbacchella** [comment]
Ok, so what is missing is more defensive code, I will have a look at that. Do you have an example of NPE stack .

**Comment by j3rem1e** [comment]
An example of a NPE for RrdDbPool.getInstance().getOpenFiles() :

```
java.lang.NullPointerException
	at org.rrd4j.core.RrdDbPool.getOpenFiles(RrdDbPool.java:117)
	at performance.rrd4j.impl.TestSamplerManager$1.failed(TestSamplerManager.java:58)
	at org.junit.rules.TestWatcher.failedQuietly(TestWatcher.java:84)
	at org.junit.rules.TestWatcher.access$300(TestWatcher.java:46)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:62)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)

```

**Comment by fbacchella** [comment]
I added safe guard in RrdDbPool in commit 7ea757230d1539fbc12893e5c838039d173c67a8. If you can test the 3.5-SNAPSHOT, I'm interested.

**Comment by j3rem1e** [comment]
I have tested the patch, but the result is not very good..

1. The NPE on getOpenFiles is already there
2. My unit test passes, but when I launch the real application, it hangs after severals minutes because the pool is full

My application is composed by one thread pusing datas to rrd files, and several threads calling DataProcessor.processData. After several minutes, all the threads are locked on a call to RrdDbPool.requestRrDb / getEntry / wait on the "full" lock.

For now, I can't reproduce this behavior with my unit test. The same codebase worked with rrd 2.2 (and ~ 20000 rrd files)

**Comment by j3rem1e** [comment]
It's probably related to the method RrdDbPool.requestRrdDb( <rrddef> ) :

This method build a new uri by calling `backend.getCanonicalUri(rrdDef.getUri())` and request an entry with this uri, but the rrddb returned reference the original uri of the rrdDef, not the "canonical" uri.

I can reproduce my bug with a junit test, and this test pass if I normalize all my uris by calling `RrdBackendFactory.findFactory(rrdDef.getUri()).getCanonicalUri(rrdDef.getUri())`

**Comment by fbacchella** [comment]
My own tests also shows a thing about URI. But I think you nailed. Thanks !

**Comment by fbacchella** [comment]
That commit: addcced383b1a069489881e8fb5846b7e5894340 should correct that.

**Comment by fbacchella** [comment]
Is RRD4J 3.5 OK for you ?
