### ISSUE TITLE
Error reading rrd file

### ISSUE THREAD

**Issue by epraja** [rrd4j/rrd4j#130]
From times to times i get an error reading an rrd file. This causes a complete loss of data and the only way is to delete the file and start from scratch.

Error:
Exception in thread "main" java.lang.IllegalArgumentException
	at java.nio.Buffer.position(Buffer.java:244)
	at org.rrd4j.core.RrdNioBackend.read(RrdNioBackend.java:172)
	at org.rrd4j.core.RrdBackend.readShort(RrdBackend.java:263)
	at org.rrd4j.core.RrdBackend.readString(RrdBackend.java:320)
	at org.rrd4j.core.RrdPrimitive.readString(RrdPrimitive.java:87)
	at org.rrd4j.core.RrdString.get(RrdString.java:33)
	at org.rrd4j.core.Datasource.dump(Datasource.java:71)
	at org.rrd4j.core.RrdDb.dump(RrdDb.java:765)
	at org.rrd4j.core.RRDReader.main(RRDReader.java:20)

Test Source:
[reader.zip](https://github.com/rrd4j/rrd4j/files/3223984/reader.zip)

RRD File:
[archivedNetworkEvents.rrd.zip](https://github.com/rrd4j/rrd4j/files/3223970/archivedNetworkEvents.rrd.zip)

**Comment by fbacchella** [comment]
with rrd4j version ?

**Comment by epraja** [comment]
RRD: 3.5
It has concurrent access for reading not for writing. 
The code i have submit is just trying a dump.

The file is located in a NFS.

**Comment by fbacchella** [comment]
Your file is totally corrupt. Check your network.

**Comment by epraja** [comment]
How do i prevent this from happening?
