### ISSUE TITLE
java.nio.channels.OverlappingFileLockException

### ISSUE THREAD

**Issue by cgaraujo** [rrd4j/rrd4j#140]
When I try to draw 2 graphs in concurrents threads using SAFE backend, I get the following exception:

java.nio.channels.OverlappingFileLockException
        at sun.nio.ch.SharedFileLockTable.checkList(FileLockTable.java:255)
        at sun.nio.ch.SharedFileLockTable.add(FileLockTable.java:152)
        at sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1107)
        at org.rrd4j.core.RrdSafeFileBackend.lockFile(RrdSafeFileBackend.java:44)
        at org.rrd4j.core.RrdSafeFileBackend.<init>(RrdSafeFileBackend.java:33)
        at org.rrd4j.core.RrdSafeFileBackendFactory.open(RrdSafeFileBackendFactory.java:52)
        at org.rrd4j.core.RrdBackendFactory.getBackend(RrdBackendFactory.java:511)
        at org.rrd4j.core.RrdDb.<init>(RrdDb.java:612)
        at org.rrd4j.core.RrdDb.<init>(RrdDb.java:44)
        at org.rrd4j.core.RrdDb$Builder.build(RrdDb.java:93)
        at org.rrd4j.data.DataProcessor.getRrd(DataProcessor.java:890)
        at org.rrd4j.data.DataProcessor.fetchRrdData(DataProcessor.java:798)
        at org.rrd4j.data.DataProcessor.processData(DataProcessor.java:649)
        at org.rrd4j.graph.RrdGraph.fetchData(RrdGraph.java:667)
        at org.rrd4j.graph.RrdGraph.createGraph(RrdGraph.java:122)
        at org.rrd4j.graph.RrdGraph.<init>(RrdGraph.java:58)

It also happens when requesting rrddb:
java.nio.channels.OverlappingFileLockException
        at sun.nio.ch.SharedFileLockTable.checkList(FileLockTable.java:255)
        at sun.nio.ch.SharedFileLockTable.add(FileLockTable.java:152)
        at sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1107)
        at org.rrd4j.core.RrdSafeFileBackend.lockFile(RrdSafeFileBackend.java:44)
        at org.rrd4j.core.RrdSafeFileBackend.<init>(RrdSafeFileBackend.java:33)
        at org.rrd4j.core.RrdSafeFileBackendFactory.open(RrdSafeFileBackendFactory.java:52)
        at org.rrd4j.core.RrdBackendFactory.getBackend(RrdBackendFactory.java:511)
        at org.rrd4j.core.RrdDb.<init>(RrdDb.java:612)
        at org.rrd4j.core.RrdDb.<init>(RrdDb.java:44)
        at org.rrd4j.core.RrdDb$Builder.build(RrdDb.java:93)
        at org.rrd4j.core.RrdDbPool.requestRrdDb(RrdDbPool.java:415)
        at org.rrd4j.core.RrdDbPool.requestRrdDb(RrdDbPool.java:346)

**Comment by fbacchella** [comment]
Using the latest snapshot ?

**Comment by cgaraujo** [comment]
Using lastest version: RRD4J 3.6

**Comment by cgaraujo** [comment]
That exception is caused when 2 threads are trying to lock the same file in the same JVM.

**Comment by fbacchella** [comment]
Do you use the RrdDbPool ? You should try 3.7-SNAPSHOT.

**Comment by cgaraujo** [comment]
Yes I use RrdDbPool.

Is 3.7-SNAPSHOT in any maven repo?

**Comment by fbacchella** [comment]
Yes, Sonatype's snapshot : https://oss.sonatype.org/content/repositories/snapshots/org/rrd4j/rrd4j/3.7-SNAPSHOT/

**Comment by cgaraujo** [comment]
Still happens with latest snapshot:

 java.nio.channels.OverlappingFileLockException
        at sun.nio.ch.SharedFileLockTable.checkList(FileLockTable.java:255)
        at sun.nio.ch.SharedFileLockTable.add(FileLockTable.java:152)
        at sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1107)
        at org.rrd4j.core.RrdSafeFileBackend.lockFile(RrdSafeFileBackend.java:44)
        at org.rrd4j.core.RrdSafeFileBackend.<init>(RrdSafeFileBackend.java:33)
        at org.rrd4j.core.RrdSafeFileBackendFactory.open(RrdSafeFileBackendFactory.java:52)
        at org.rrd4j.core.RrdBackendFactory.getBackend(RrdBackendFactory.java:511)
        at org.rrd4j.core.RrdDb.<init>(RrdDb.java:625)
        at org.rrd4j.core.RrdDb.<init>(RrdDb.java:44)
        at org.rrd4j.core.RrdDb$Builder.build(RrdDb.java:93)
        at org.rrd4j.data.DataProcessor.lambda$fetchRrdData$2(DataProcessor.java:992)
        at java.util.HashMap.computeIfAbsent(HashMap.java:1127)
        at org.rrd4j.data.DataProcessor.fetchRrdData(DataProcessor.java:988)
        at org.rrd4j.data.DataProcessor.processData(DataProcessor.java:846)
        at org.rrd4j.graph.RrdGraph.fetchData(RrdGraph.java:674)
        at org.rrd4j.graph.RrdGraph.createGraph(RrdGraph.java:126)
        at org.rrd4j.graph.RrdGraph.<init>(RrdGraph.java:62)

**Comment by fbacchella** [comment]
In the shown stack, pool is not used. Did you call org.rrd4j.graph.RrdGraphDef.setPool(RrdDbPool) ?

**Comment by cgaraujo** [comment]
I started to use the pool in the RrdGraphDef and the problem disappeared.
When will version 3.7 be released?

**Comment by fbacchella** [comment]
Soon, I just time to check that everything is OK.

**Comment by fbacchella** [comment]
3.7 is just released.
