### ISSUE TITLE
How to recreate the db file if it is broken externally?

### ISSUE THREAD

**Issue by lanmaster** [rrd4j/rrd4j#143]
For now i use this code to check that db file is valid:
```
private static boolean checkDbFileValid() {
        boolean result = true;
        try (RrdDb rrdDb = RrdDb.getBuilder().setPath(RRD_FILE_PATH).setPool(RRD_DB_POOL).build()) {
        } catch (Exception e) {
            log.error("RRDB. Checking RRD File fault.", e);
            result = false;
        }
        return result;
}
```
But i can't remove db file after that, delete code:
```
        boolean dbFileValid = checkDbFileValid();
        if (!dbFileValid) {
            Path path = Paths.get(RRD_FILE_PATH);
            try {
                if (Files.deleteIfExists(path)) {
                    log.info("RRDB. File '{}' corrupted. Deleting...", RRD_FILE_PATH);
                }
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
```

It throws exception:
```
java.nio.file.AccessDeniedException: _rddb\simple_datasource.rrd
	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:89)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:274)
	at java.base/sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:110)
	at java.base/java.nio.file.Files.deleteIfExists(Files.java:1181)
```

**Comment by fbacchella** [comment]
What make you think that's a bug in RRD4J ?

**Comment by lanmaster** [comment]
I think maybe somrthing inside RRD4J locking file access... Is it wrong?

**Comment by fbacchella** [comment]
Try without the pool

**Comment by lanmaster** [comment]
I triyed and get same result. By the way, an exception from RRD4J: 
```
java.lang.IndexOutOfBoundsException: null
	at java.base/java.nio.Buffer.checkIndex(Buffer.java:693)
	at java.base/java.nio.DirectByteBuffer.getInt(DirectByteBuffer.java:758)
	at org.rrd4j.core.ByteBufferBackend.readInt(ByteBufferBackend.java:130)
	at org.rrd4j.core.RrdPrimitive.readInt(RrdPrimitive.java:38)
	at org.rrd4j.core.RrdInt.get(RrdInt.java:35)
	at org.rrd4j.core.Archive.<init>(Archive.java:45)
	at org.rrd4j.core.RrdDb.<init>(RrdDb.java:646)
	at org.rrd4j.core.RrdDb.<init>(RrdDb.java:44)
	at org.rrd4j.core.RrdDb$Builder.build(RrdDb.java:94)
```
For information, on stopped application i edit rrd file and add some random chars in the middle. Then i start app and triyng to delete file from app.

**Comment by fbacchella** [comment]
So rrd4j fails on corrupted files ? That's not a bug.  An neither the access denied. It's probably coming from outside rrd4j.
